export const RESPONSE_CODES = {
	UNKNOWN_ERROR: 'UNKNOWN_ERROR',
	OK: 'OK',
	NOT_FOUND: 'NOT_FOUND',
	BAD_INPUT: 'BAD_INPUT',
	DRIVE_INIT_FAILED: 'DRIVE_INIT_FAILED',
	UPLOAD_FAILED: 'UPLOAD_FAILED'
} as const;
